ddr_geo_example_base_homepage:
    path:     /
    defaults: { _controller: DdrGeoExampleBaseBundle:Default:index }

ddr_geo_example_city_detail:
    path: /city/{id}
    defaults: { _controller: DdrGeoExampleBaseBundle:Default:cityDetail }

ddr_geo_example_location:
    path: /location
    defaults: { _controller: DdrGeoExampleBaseBundle:Default:location }