services:
#    ddr_geo_example_base.example:
#        class: Net\Dontdrinkandroot\GeoExample\BaseBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ddr_geo_example.service.geo:
        class: Net\Dontdrinkandroot\GeoExample\BaseBundle\Service\GeoService
        arguments: [@doctrine.dbal.default_connection]